### ISSUE TITLE
CO (colchester) appearing in a south west report

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/standard-reports-ui#1]
I created a basic report for the south west, split by postcode and it contains one record for CO which appears to be colchester.
report details:
 report type is average prices and volumes
area type is region
country is England and Wales
aggregate data by pcArea
dates are year to date
age of property is any 

[avgPrice-region-SOUTH_WEST-by-pcArea-any-2015.txt](https://github.com/epimorphics/standard-reports-ui/files/54067/avgPrice-region-SOUTH_WEST-by-pcArea-any-2015.txt)

**Comment by der** [comment]
This is due to a single odd data record:

http://landregistry.data.gov.uk/data/ppi/transaction/7CE137FD-B1FC-4CEC-8086-3B38421C6541/current 

This record is give as have county and district of BANES (and thus in region South West) but with a Colchester postcode and town.

So I think the report manager is correctly showing what it is in the data and it's the data itself that is at fault.

**Comment by MalcolmShazell** [comment]
ok i'll take it away and see if we can't get it fixed for the january data release
