### ISSUE TITLE
TA results in SR don't seem to match what comes out of the report builder

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/standard-reports-ui#2]
I'm trying to get a handle on how we can automatically validate the results presented against the data in the triple store.

I selected the following for Devon
 report type is average prices and volumes
area type is county
country is England and Wales
aggregate data by pcArea
dates are year to date
age of property is any 

got the following results
[avgPrice-county-DEVON-by-pcArea-any-2015.txt](https://github.com/epimorphics/standard-reports-ui/files/58097/avgPrice-county-DEVON-by-pcArea-any-2015.txt)

TA has 0 flat maisonette sale - however if I select TA21 in report builder I'm getting lots of results. Now very confused :) same with DT 
neither are postcodes I'd expect for devon so are we starting to uncover more data issues?

**Comment by der** [comment]
There might be data issues but here I think it's just that post code areas don't line up nicely with counties/districts.

What happens is that the filter settings (in this case county=Devon, year=2015) decide what transactions to aggregate over, then the results for all those transactions are accumulated against the chosen aggregation selection.

So in scanning Devon it found 14 properties that were given a TAxx postcode.

When you go to TA21 in the report builder and look down you'll see that most of those say "Somerset" rather than "Devon" so they won't appear in your standard report. Whether that's correct or not I can't tell for sure but seems reasonable. Wikipedia seems to that most of TA is Somerset but does seem to think that some of TA21 spills over into Devon. 

If you try the report builder asking for postcode=ta21 county=devon and year=2015 then you get 12 results [ppd1](landregistry.data.gov.uk/app/ppd/search?county=Devon&et%5B%5D=lrcommon%3Afreehold&et%5B%5D=lrcommon%3Aleasehold&limit=100&max_date=31+October+2015&min_date=1+January+2015&nb%5B%5D=true&nb%5B%5D=false&postcode=ta21&ptype%5B%5D=lrcommon%3Adetached&ptype%5B%5D=lrcommon%3Asemi-detached&ptype%5B%5D=lrcommon%3Aterraced&ptype%5B%5D=lrcommon%3Aflat-maisonette&ptype%5B%5D=lrcommon%3AotherPropertyType&tc%5B%5D=ppd%3AstandardPricePaidTransaction&tc%5B%5D=ppd%3AadditionalPricePaidTransaction)

You can't ask for postcode=ta through the report builder directly but you can take the SPARQL query it generates (thanks Ian) and edit it to be a wildcard search for "TA*" postcodes and that gives you 15 results [sparql1](http://landregistry.data.gov.uk/app/hpi/qonsole?q=PREFIX%20%20text:%20%3Chttp://jena.apache.org/text%23%3E%0APREFIX%20%20xsd:%20%20%3Chttp://www.w3.org/2001/XMLSchema%23%3E%0APREFIX%20%20ppd:%20%20%3Chttp://landregistry.data.gov.uk/def/ppi/%3E%0APREFIX%20%20lrcommon:%20%3Chttp://landregistry.data.gov.uk/def/common/%3E%0A%0ASELECT%20%20?item%20?ppd_propertyAddress%20?ppd_transactionDate%20?ppd_hasTransaction%20?ppd_pricePaid%20?ppd_transactionCategory%20?ppd_transactionId%20?ppd_estateType%20?ppd_newBuild%20?ppd_propertyAddressCounty%20?ppd_propertyAddressDistrict%20?ppd_propertyAddressLocality%20?ppd_propertyAddressPaon%20?ppd_propertyAddressPostcode%20?ppd_propertyAddressSaon%20?ppd_propertyAddressStreet%20?ppd_propertyAddressTown%20?ppd_propertyType%20?ppd_recordStatus%0AWHERE%0A%20%20%7B%20?ppd_propertyAddress%20text:query%20_:b0%20.%0A%20%20%20%20_:b0%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23first%3E%20%22county:%20(%20Devon%20)%20%20AND%20postcode:%20(%20ta%20)%22%20.%0A%20%20%20%20_:b0%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23rest%3E%20_:b1%20.%0A%20%20%20%20_:b1%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23first%3E%203000000%20.%0A%20%20%20%20_:b1%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23rest%3E%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23nil%3E%20.%0A%20%20%20%20?item%20ppd:propertyAddress%20?ppd_propertyAddress%20.%0A%20%20%20%20?item%20ppd:transactionDate%20?ppd_transactionDate%20.%0A%20%20%20%20?item%20ppd:hasTransaction%20?ppd_hasTransaction%20.%0A%20%20%20%20?item%20ppd:pricePaid%20?ppd_pricePaid%20.%0A%20%20%20%20?item%20ppd:transactionCategory%20?ppd_transactionCategory%20.%0A%20%20%20%20?item%20ppd:transactionId%20?ppd_transactionId%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?item%20ppd:estateType%20?ppd_estateType%20%7D%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?item%20ppd:newBuild%20?ppd_newBuild%20%7D%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?ppd_propertyAddress%20lrcommon:county%20?ppd_propertyAddressCounty%20%7D%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?ppd_propertyAddress%20lrcommon:district%20?ppd_propertyAddressDistrict%20%7D%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?ppd_propertyAddress%20lrcommon:locality%20?ppd_propertyAddressLocality%20%7D%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?ppd_propertyAddress%20lrcommon:paon%20?ppd_propertyAddressPaon%20%7D%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?ppd_propertyAddress%20lrcommon:postcode%20?ppd_propertyAddressPostcode%20%7D%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?ppd_propertyAddress%20lrcommon:saon%20?ppd_propertyAddressSaon%20%7D%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?ppd_propertyAddress%20lrcommon:street%20?ppd_propertyAddressStreet%20%7D%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?ppd_propertyAddress%20lrcommon:town%20?ppd_propertyAddressTown%20%7D%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?item%20ppd:propertyType%20?ppd_propertyType%20%7D%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?item%20ppd:recordStatus%20?ppd_recordStatus%20%7D%0A%20%20%20%20FILTER%20(%20?ppd_transactionDate%20%3E=%20%222015-01-01%22%5E%5Exsd:date%20)%0A%20%20%20%20FILTER%20(%20?ppd_transactionDate%20%3C=%20%222015-10-31%22%5E%5Exsd:date%20)%0A%20%20%7D%0ALIMIT%20%20%20100%0A).

So why 15 results when the report generator only says 14? That's because the second one of those (Unit 10, 	GREENHAM BUSINESS PARK) is of type "Other" and so is filtered out.

**Comment by MalcolmShazell** [comment]
looking at it a bit closer we seem to have wellington existing both in mid devon and somerset - which may or may not be correct but seems a bit odd - i'll push this over to the people in the know - however they are both off until monday - so i'll keep this open until I get an answer from them.

**Comment by MalcolmShazell** [comment]
sorry should have closed this along time ago - devon was reporting correctly - we just need to be careful with oddball postcodes where we don't expect them
