### ISSUE TITLE
Your Report File page loses infromation in Chrome

### ISSUE THREAD

**Issue by carl-t** [epimorphics/standard-reports-ui#20]
This only seems to occur in Chrome so it could be a browser issue.

At the end of the report generation process I see the "Your report file" page with links to my report.  I then click (browser) back, and (browser) forwards to return to the generated reports page.  On Chrome the page loses all the HTML formatting information:

![image](https://cloud.githubusercontent.com/assets/16542988/13255988/aa170d02-da40-11e5-9b56-1cdb82d074eb.png)

**Comment by der** [comment]
Have seen this too under Chrome.

If you refresh the page the styling reappears.

If you have devtools open (disabling caching) the problem does not occur.

**Comment by ijdickinson** [comment]
This turns out not to be a caching issue. Rather, Chrome is helpfully remembering that the last time it accessed the page URL it was via an Ajax request, so when returning to the back via a 'back' action it replays the request with an `X-REQUESTED-WITH` header set to indicate an Ajax request. This in turn only reloads a partial page.

The fix here is to change the request processing in the controller to not rely on the `.xhr?` method to detect incoming Ajax requests.

**Comment by ijdickinson** [comment]
Fixed on beta server

**Comment by carl-t** [comment]
Sweet.
